-- MUESTRA EL LISTADO DE EVENTOS, (TALLRES (T), CURSOS LIBRES (C), Y CONVOCATORIAS(V) )
CREATE OR REPLACE VIEW LISTA_EVENTOS AS
select NOMBRE, DESCRIPCION, TIPO_TALLER
from	TALLER
UNION
SELECT NOMBRE, DESCRIPCION, 'V'
FROM CONVOCATORIA;


-- MUESTRA EL NOMBRE DE LOS USUARIOS Y SU RESPECTIVO EMAIL
CREATE OR REPLACE VIEW USUARIO_NOMBRE AS
SELECT 	NOMBRES||' '||APELLIDOS AS NOMBRE, EMAIL
FROM 	USUARIO;


-- MUESTRA LOS EVENTOS EN LOS QUE ESTÁ INSCRITO UN USUARIO.
CREATE OR REPLACE VIEW EVENTO_BY_USER AS
SELECT USUARIO.EMAIL, TALLER.NOMBRE, TALLER.DESCRIPCION, TALLER.TIPO_TALLER
from USUARIO JOIN USUARIO_TALLER
		ON(USUARIO.ID_USUARIO = USUARIO_TALLER.ID_USUARIO) JOIN TALLER
		ON(USUARIO_TALLER.ID_TALLER = TALLER.ID_TALLER)
union

SELECT USUARIO.EMAIL, CONVOCATORIA.NOMBRE, CONVOCATORIA.DESCRIPCION, 'V'
from USUARIO JOIN USUARIO_CONVOCATORIA
		ON(USUARIO.ID_USUARIO = USUARIO_CONVOCATORIA.ID_USUARIO) JOIN CONVOCATORIA
		ON(USUARIO_CONVOCATORIA.ID_CONVOCATORIA = CONVOCATORIA.ID_CONVOCATORIA);


-- MUESTRA EL ID DE USUARIOS VINCULADOS A UN TALLER COMO ESTUDIANTE O COMO PROFESOR
create or replace view USUARIO_PROFESOR_TALLER AS

select ID_USUARIO, ID_TALLER, 'U' T_VINCULACION
from USUARIO_TALLER 

UNION

select ID_PROFESOR, ID_TALLER, 'P'
from PROFESOR_TALLER
