
package co.edu.UNal.ArquitecturaDeSoftware.Bienestar.Control.Servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BestStudents", targetNamespace = "http://Service/", wsdlLocation = "http://localhost:8080/EntidadEducativa/BestStudents?wsdl")
public class BestStudents_Service
    extends Service
{

    private final static URL BESTSTUDENTS_WSDL_LOCATION;
    private final static WebServiceException BESTSTUDENTS_EXCEPTION;
    private final static QName BESTSTUDENTS_QNAME = new QName("http://Service/", "BestStudents");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EntidadEducativa/BestStudents?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BESTSTUDENTS_WSDL_LOCATION = url;
        BESTSTUDENTS_EXCEPTION = e;
    }

    public BestStudents_Service() {
        super(__getWsdlLocation(), BESTSTUDENTS_QNAME);
    }

    public BestStudents_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BESTSTUDENTS_QNAME, features);
    }

    public BestStudents_Service(URL wsdlLocation) {
        super(wsdlLocation, BESTSTUDENTS_QNAME);
    }

    public BestStudents_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BESTSTUDENTS_QNAME, features);
    }

    public BestStudents_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BestStudents_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BestStudents
     */
    @WebEndpoint(name = "BestStudentsPort")
    public BestStudents getBestStudentsPort() {
        return super.getPort(new QName("http://Service/", "BestStudentsPort"), BestStudents.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BestStudents
     */
    @WebEndpoint(name = "BestStudentsPort")
    public BestStudents getBestStudentsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service/", "BestStudentsPort"), BestStudents.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BESTSTUDENTS_EXCEPTION!= null) {
            throw BESTSTUDENTS_EXCEPTION;
        }
        return BESTSTUDENTS_WSDL_LOCATION;
    }

}
